---
- hosts: localhost
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: linuxVMRg
      allocation_method: Static
      name: ansvmip
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: linuxVMRg
      name: nicansi
      virtual_network: linuxVnet
      subnet: linuxSubnet
      public_ip_name: ansvmip
  - name: Create a VM with resource group and vnet
    azure_rm_virtualmachine:
      resource_group: linuxVMRg
      name: ansiblevm
      vm_size: Standard_DS1_v2
      managed_disk_type: Premium_LRS
      admin_username: vmadmin
      ssh_password_enabled: false
      ssh_public_keys:
      - path: /home/vmadmin/.ssh/authorized_keys
        key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCp/EvmYYj3WEt8wHMpDoKzm38K0ni96F0L5UrCBX92o02KQQztOIkH/+eMByItPY2VUkN0hf7WEOQLL54YbXDFcezAdN8+R4g3vLdCUQLWdt6Fpl9pCSOYMhAUGkahX5Ww9M5YSFZmignw7bVkxEhugODKwC66eClnSL1k6KVZZ+qP5S2TzK4ji/CyEoae2/FsOrCZm/GsyEC1PXtB6CFNdwKrtMLKXp1S3QvPusW65+1e7DJ5O4ba1rS1BHMRm8WEoMHQomoL1N6567SsXAsNTBid/5nEwrmhVm9mpQO2fNypQtcoLDw37nN1DjTmgJKpvpwVtegL6yb6DrPmC8OH vmadmin@linuxVM2"
      network_interfaces: nicansi
      os_type: Linux
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 18.04-LTS
        version: latest
