---
- hosts: all
  become: true
  tasks:
  - name: update python apt
    apt:
      name: python-apt
      state: latest
      update_cache: yes
      
  - name: update and upgrade apt packages
    apt:
      update_cache: yes
      upgrade: 'yes'
     
  - name: install docker
    apt:
      name:  docker*
      state: present 
      update_cache: yes
  - name: start docker service
    service:
      name: docker 
      state: started
      enabled: yes